import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  plannerSidebar: [{ type: 'autogenerated', dirName: 'planner' }],
  engineSidebar: [{ type: 'autogenerated', dirName: 'engine' }],
};

export default sidebars;
