import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['why-openexec', 'engine/intro'],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'engine/concepts/dcp',
        'engine/concepts/blueprints',
        'lifecycle',
        'engine/concepts/state-management',
        'engine/concepts/configuration',
      ],
    },
    {
      type: 'category',
      label: 'User Guides',
      items: [
        'engine/usage/wizard',
        'engine/usage/cli-reference',
        'engine/usage/status',
        'engine/usage/safe-commit',
      ],
    },
    {
      type: 'category',
      label: 'Legacy Packages (Deprecated)',
      items: [{ type: 'autogenerated', dirName: 'planner' }],
      collapsible: true,
      collapsed: true,
    }
  ],
};

export default sidebars;
