import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: 'engine' },
    {
      type: 'category',
      label: 'Legacy Packages (Deprecated)',
      items: [{ type: 'autogenerated', dirName: 'planner' }],
      collapsible: true,
      collapsed: true,
    }
  ],
};

export default sidebars;
